version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  pre_build:
    commands:
    # ffmpeg
      - sudo su
      - cd /usr/local/bin
      - mkdir ffmpeg
      - cd ffmpeg
      - wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
      - tar -xvf ffmpeg-git-amd64-static.tar.xz
      - ln -s /usr/local/bin/ffmpeg/ffmpeg /usr/bin/ffmpeg
      # node
      - curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
      - sudo yum install -y nodejs
      - sudo yum install gcc-c++ make -y
      # yarn and extra npm global packages
      - npm install yarn -g
      - npm i -g @nestjs/cli
      - npm install -g typescript
      
      
  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths